server:
  port: 8081
spring:
  messages:
    encoding: UTF-8
  dubbo:
    application:
      name: manager
    base-package: com.cool.wendao.manager
    registry:
#      protocol: nacos
      address: 127.0.0.1
      port: 2181
    consumer:
      timeout: 1000
      check: true
      retries: 2
  freemarker:
    request-context-attribute: application
    settings:
      number_format: '0.########'
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  level:
    root: info
request_image_url: http://127.0.0.1:8080/