package org.linlinjava.litemall.gameserver.domain;

import java.util.HashMap;
import java.util.Map;

public class ZbAttribute {

    public int id;
    public int phy_power;
    public int mag_power;
    public int speed;
    public int life;
    public int skill_low_cost;
    public int mstunt_rate;
    public int wood;
    public int water;
    public int fire;
    public int earth;
    public int resist_metal;
    public int damage_sel;
    public int stunt_rate;
    public int double_hit_rate;
    public int release_forgotten;
    public int ignore_all_resist_except;
    public int stunt;
    public int def;
    public int dex;
    public int wiz;
    public int family;
    public int life_recover;
    public int all_skill;
    public int portrait;
    public int resist_frozen;
    public int resist_sleep;
    public int resist_forgotten;
    public int resist_confusion;
    public int longevity;
    public int resist_wood;
    public int resist_water;
    public int resist_fire;
    public int resist_earth;
    public int exp_to_next_level;
    public int all_resist_except;
    public int accurate;
    public int mana;
    public int parry;
    public int super_excluse_wood;
    public int super_excluse_water;
    public int super_excluse_fire;
    public int super_excluse_earth;
    public int B_skill_low_cost;
    public int enhanced_wood;
    public int enhanced_water;
    public int enhanced_fire;
    public int enhanced_earth;
    public int mag_dodge;
    public int ignore_mag_dodge;
    public int jinguang_zhaxian_counter_att_rate;
    public int C_skill_low_cost;
    public int D_skill_low_cost;
    public int super_poison;
    public int ignore_resist_wood;
    public int ignore_resist_water;
    public int ignore_resist_fire;
    public int ignore_resist_earth;
    public int ignore_resist_forgotten;
    public int super_confusion;
    public int super_sleep;
    public int enhanced_metal;
    public int super_forgotten;
    public int super_frozen;
    public int ignore_resist_frozen;
    public int ignore_resist_sleep;
    public int ignore_resist_confusion;
    public int super_excluse_metal;
    public int ignore_resist_poison;
    public int tao_ex;
    public int release_confusion;
    public int release_sleep;
    public int release_frozen;
    public int release_poison;

}
