spring:
  messages:
    encoding: UTF-8
  dubbo:
    application:
      name: gameserver
    base-package: org.linlinjava.litemall.gameserver.game
    registry:
      protocol: nacos
      address: 127.0.0.1
      port: 8848
    consumer:
      timeout: 1000
      check: false
      retries: 2
netty:
  port: 14721
  url: coolwendao.xicp.io
  ip: coolwendao.xicp.io
