spring:
  messages:
    encoding: UTF-8
  dubbo:
    application:
      name: gameserver
    base-package: org.linlinjava.litemall.gameserver.game
    registry:
#      protocol: nacos
      address: 127.0.0.1
      port: 2181
    consumer:
      timeout: 1000
      check: false
      retries: 2
logging:
  level:
    root: info
    c.a: error
netty:
  port: 14721
  url: coolwendao.xicp.io
  ip: coolwendao.xicp.io
