spring:
  messages:
    encoding: UTF-8
  redis:
    database: 0
    host: 113.142.69.199
    port: 6379
    password: 123456
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  dubbo:
    application:
      name: web
    base-package: org.linlinjava.litemall.wx
    registry:
      address: 127.0.0.1
      port: 2181
    consumer:
      timeout: 1000
      check: false
      retries: 2
logging:
  level:
    root: info

server:
  port: 81
netty:
  port: 14721
  ip: 0.0.0.0
  url: s.fiuwbjadshf.com

