server:
spring:
  dubbo:
    application:
      name: servicedata
    base-package: com.cool.wendao.*.impl
    registry:
      protocol: nacos
      address: 127.0.0.1
      port: 8848
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    password: admin123456
#    username: admin
#    url: jdbc:mysql://113.142.69.199/gserver?useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&characterEncoding=UTF-8&useAffectedRows=true
    password: root
    username: root
    url: jdbc:mysql://127.0.0.1/gs?useUnicode=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&characterEncoding=UTF-8&useAffectedRows=true
logging:
  level:
    root: info
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations:
    - classpath*:com/cool/wendao/*/dao/mapper/*.xml