spring:
  messages:
    encoding: UTF-8
  dubbo:
    application:
      name: web
    base-package: org.linlinjava.litemall.wx
    registry:
#      protocol: nacos
      address: 127.0.0.1
      port: 2181
    consumer:
      timeout: 1000
      check: false
      retries: 2
logging:
  level:
    root: info
server:
  port: 81
netty:
  port: 14721
  ip: 0.0.0.0
  url: coolwendao.xicp.io
groups: 梦想问道
groupsL: '["一战功成"] = { aaa = "coolwendao.xicp.io:14721", group = "梦想问道", state = 4, isNew = true },'

